
#pragma once

#define MYICON 101

//************************ Sir's Audio ************************
#define KALLA_KA_SANGA_MALA 1


#define MYIMAGE_ASTROMEDICOMP_BITMAP 102

#define MYIMAGE_ORTHO_BITMAP 103

#define MYIMAGE_TECHUSED_BITMAP 104

#define MYIMAGE_GROUPMEMBERS_BITMAP 105

#define MYIMAGE_GROUPLEADER_BITMAP 106

#define MYIMAGE_MADAM_BITMAP 107

#define MYIMAGE_SIR_BITMAP 108

